# Generated by Django 6.0.2 on 2026-02-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Мой магазин одежды', max_length=200)),
                ('site_description', models.TextField(default='Лучший магазин одежды в Бишкеке')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('email', models.EmailField(default='info@shop.kg', max_length=254)),
                ('phone', models.CharField(default='+996 999 123 456', max_length=50)),
                ('currency', models.CharField(default='KGS', max_length=10)),
                ('currency_symbol', models.CharField(default='сом', max_length=5)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
