# Generated by Django 6.0.2 on 2026-02-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='products/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
