# Generated by Django 6.0.2 on 2026-02-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
