# Generated by Django 6.0.2 on 2026-02-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
    ]
