# Generated by Django 6.0.2 on 2026-02-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='additional_price',
        ),
    ]
